/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = 'qpttobsxyvmaxtmzcver';
export const publicAnonKey =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwdHRvYnN4eXZtYXh0bXpjdmVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0MDE4NTUsImV4cCI6MjA4OTk3Nzg1NX0.ytHD0kdHQZHxhEjc0j43GnWYHBeVI74eeLImSsbu1Z8';
