-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.kv_store_7d36b31f (
  key text NOT NULL,
  value jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT kv_store_7d36b31f_pkey PRIMARY KEY (key)
);
CREATE TABLE public.enterprises (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text,
  plan text DEFAULT 'basic'::text,
  subscription_status text DEFAULT 'active'::text,
  max_users integer DEFAULT 5,
  created_at timestamp with time zone DEFAULT now(),
  rut character varying,
  plan_price numeric,
  auditoria_pagada boolean DEFAULT false,
  primer_mes_pagado boolean DEFAULT false,
  updated_at timestamp with time zone DEFAULT now(),
  recommended_plan text,
  telefono text,
  suspension_reason text,
  suspended_at timestamp with time zone,
  CONSTRAINT enterprises_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_enterprises (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  enterprise_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'employee'::text,
  is_active boolean DEFAULT true,
  assigned_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_enterprises_pkey PRIMARY KEY (id),
  CONSTRAINT user_enterprises_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_enterprises_enterprise_id_fkey FOREIGN KEY (enterprise_id) REFERENCES public.enterprises(id)
);
CREATE TABLE public.documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  enterprise_id uuid NOT NULL,
  user_id uuid,
  filename text NOT NULL,
  original_name text NOT NULL,
  file_type text,
  file_category text DEFAULT 'other'::text,
  file_size integer,
  mime_type text,
  storage_path text,
  storage_url text,
  description text,
  tags ARRAY,
  uploaded_by uuid NOT NULL,
  uploaded_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  hash_sha256 character varying,
  empleado_id uuid,
  version_actual_id uuid,
  recipient_type character varying CHECK (recipient_type::text = ANY (ARRAY['admin'::character varying, 'worker'::character varying, 'enterprise'::character varying]::text[])),
  legal_category_code character varying,
  CONSTRAINT documents_pkey PRIMARY KEY (id),
  CONSTRAINT documents_empleado_id_fkey FOREIGN KEY (empleado_id) REFERENCES public.empleados(id),
  CONSTRAINT documents_version_actual_id_fkey FOREIGN KEY (version_actual_id) REFERENCES public.documento_version(id),
  CONSTRAINT fk_documents_legal_category FOREIGN KEY (legal_category_code) REFERENCES public.document_legal_categories(codigo),
  CONSTRAINT documents_enterprise_id_fkey FOREIGN KEY (enterprise_id) REFERENCES public.enterprises(id)
);
CREATE TABLE public.empleados (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL,
  rut character varying NOT NULL UNIQUE,
  nombre character varying NOT NULL,
  apellido character varying NOT NULL,
  email character varying UNIQUE,
  telefono character varying,
  departamento character varying,
  cargo character varying,
  fecha_contratacion date,
  tipo_contrato character varying DEFAULT 'indefinido'::character varying,
  salario numeric,
  activo boolean DEFAULT true,
  fecha_desvinculacion date,
  motivo_desvinculacion text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT empleados_pkey PRIMARY KEY (id),
  CONSTRAINT empleados_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.enterprises(id),
  CONSTRAINT empleados_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.cargas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empleado_id uuid NOT NULL,
  rut character varying,
  nombre character varying NOT NULL,
  apellido character varying NOT NULL,
  parentesco character varying NOT NULL,
  fecha_nacimiento date,
  fecha_vencimiento_carga date,
  activa boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT cargas_pkey PRIMARY KEY (id),
  CONSTRAINT cargas_empleado_id_fkey FOREIGN KEY (empleado_id) REFERENCES public.empleados(id)
);
CREATE TABLE public.documento_version (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  documento_id uuid NOT NULL,
  numero_version integer NOT NULL,
  archivo_path character varying NOT NULL,
  archivo_nombre character varying NOT NULL,
  hash_sha256 character varying NOT NULL,
  tamano_bytes bigint,
  mime_type character varying,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  cambios_descripcion text,
  CONSTRAINT documento_version_pkey PRIMARY KEY (id),
  CONSTRAINT documento_version_documento_id_fkey FOREIGN KEY (documento_id) REFERENCES public.documents(id),
  CONSTRAINT documento_version_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL,
  plan character varying NOT NULL DEFAULT 'basic'::character varying,
  estado character varying NOT NULL DEFAULT 'trial'::character varying,
  fecha_inicio date NOT NULL,
  fecha_fin date,
  fecha_cancelacion date,
  incluye_ia boolean DEFAULT false,
  limite_consultas_ia integer DEFAULT 0,
  consultas_realizadas integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  ultimo_pago_id uuid,
  proximo_pago_fecha date,
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.enterprises(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subscription_id uuid,
  monto numeric NOT NULL,
  moneda character varying DEFAULT 'CLP'::character varying,
  estado character varying NOT NULL DEFAULT 'pending'::character varying,
  referencia_flow character varying,
  flow_order_id character varying,
  fecha_creacion timestamp without time zone DEFAULT now(),
  fecha_pago timestamp without time zone,
  fecha_vencimiento date,
  flow_response jsonb,
  confirmed_by_webhook boolean DEFAULT false,
  webhook_timestamp timestamp without time zone,
  empresa_id uuid,
  plan text,
  concepto text,
  metodo_pago text,
  transaction_id text,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE public.notificaciones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  titulo character varying NOT NULL,
  mensaje text NOT NULL,
  tipo character varying DEFAULT 'info'::character varying,
  link character varying,
  link_text character varying,
  leida boolean DEFAULT false,
  fecha_leida timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  created_by uuid,
  expires_at timestamp without time zone,
  CONSTRAINT notificaciones_pkey PRIMARY KEY (id),
  CONSTRAINT notificaciones_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT notificaciones_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  action character varying NOT NULL,
  user_id uuid,
  resource_type character varying,
  resource_id uuid,
  resource_path text,
  enterprise_id uuid,
  success boolean DEFAULT true,
  error_message text,
  ip_address inet,
  user_agent text,
  hash_sha256 character varying,
  metadata jsonb,
  timestamp timestamp without time zone DEFAULT now(),
  created_at timestamp without time zone DEFAULT now(),
  hash_prev text,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT audit_logs_enterprise_id_fkey FOREIGN KEY (enterprise_id) REFERENCES public.enterprises(id)
);
CREATE TABLE public.document_views (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL,
  viewer_id uuid NOT NULL,
  viewer_email text,
  viewer_nombre text,
  viewer_empresa_id uuid,
  owner_id uuid NOT NULL,
  owner_email text,
  owner_nombre text,
  owner_empresa_id uuid,
  action_type character varying NOT NULL CHECK (action_type::text = ANY (ARRAY['view'::character varying, 'download'::character varying, 'share'::character varying]::text[])),
  ip_address inet,
  user_agent text,
  viewed_at timestamp without time zone DEFAULT now(),
  audit_log_id uuid,
  CONSTRAINT document_views_pkey PRIMARY KEY (id),
  CONSTRAINT document_views_viewer_empresa_id_fkey FOREIGN KEY (viewer_empresa_id) REFERENCES public.enterprises(id),
  CONSTRAINT document_views_owner_empresa_id_fkey FOREIGN KEY (owner_empresa_id) REFERENCES public.enterprises(id),
  CONSTRAINT document_views_audit_log_id_fkey FOREIGN KEY (audit_log_id) REFERENCES public.audit_logs(id),
  CONSTRAINT document_views_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id)
);
CREATE TABLE public.document_legal_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  codigo character varying NOT NULL UNIQUE,
  nombre character varying NOT NULL,
  descripcion text,
  tipo_documento character varying NOT NULL,
  normativa_referencia text,
  es_obligatorio boolean DEFAULT false,
  plazo_conservacion_anos integer,
  aplicabilidad character varying CHECK (aplicabilidad::text = ANY (ARRAY['trabajador'::character varying, 'empresa'::character varying, 'ambos'::character varying]::text[])),
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  activo boolean DEFAULT true,
  CONSTRAINT document_legal_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.loy_knowledge_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  content text NOT NULL,
  content_chunk text,
  embedding USER-DEFINED,
  source_url text,
  source_type character varying,
  source_name character varying,
  category character varying,
  published_date date,
  effective_date date,
  chunk_index integer DEFAULT 0,
  total_chunks integer DEFAULT 1,
  status character varying DEFAULT 'pending'::character varying,
  validated_by uuid,
  validated_at timestamp without time zone,
  validation_notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT loy_knowledge_documents_pkey PRIMARY KEY (id),
  CONSTRAINT loy_knowledge_documents_validated_by_fkey FOREIGN KEY (validated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.loy_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  enterprise_id uuid,
  title character varying,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT loy_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT loy_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT loy_conversations_enterprise_id_fkey FOREIGN KEY (enterprise_id) REFERENCES public.enterprises(id)
);
CREATE TABLE public.loy_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid,
  role character varying NOT NULL,
  content text NOT NULL,
  sources_used jsonb DEFAULT '[]'::jsonb,
  model_used character varying,
  tokens_used integer,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT loy_messages_pkey PRIMARY KEY (id),
  CONSTRAINT loy_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.loy_conversations(id)
);
CREATE TABLE public.loy_spider_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  spider_name character varying NOT NULL,
  source_url text NOT NULL,
  status character varying NOT NULL,
  items_found integer DEFAULT 0,
  items_processed integer DEFAULT 0,
  error_message text,
  execution_time_ms integer,
  raw_data jsonb,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT loy_spider_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL,
  tipo text NOT NULL CHECK (tipo = ANY (ARRAY['pago_exitoso'::text, 'pago_pendiente'::text, 'recordatorio'::text, 'suspension'::text, 'general'::text])),
  titulo text NOT NULL,
  mensaje text NOT NULL,
  leida boolean DEFAULT false,
  fecha_creacion timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pending_emails (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  to_email text NOT NULL,
  template text NOT NULL,
  template_data jsonb,
  status text DEFAULT 'pending'::text,
  attempts integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pending_emails_pkey PRIMARY KEY (id)
);